USE CAMELBEE_MARIADB;

CREATE USER 'camelbee_user'@'localhost' IDENTIFIED BY 'secret';

GRANT ALL PRIVILEGES ON *.* TO 'camelbee_user'@'%';

FLUSH PRIVILEGES;

CREATE TABLE camelbee_musicians_table
(
    ID INT(11) NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255),
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE camelbee_songs_table
(
    ID INT(11) NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) ,
    COMPOSER VARCHAR(255) ,
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

